In [30]:
import pandas as pd
import numpy as np

In [31]:
df=pd.read_csv("../data/raw/data_after_eda.csv")

In [32]:
df.head(5)

,Rating,Company Name,Job Title,Salary,Salaries Reported,Location,Employment Status,Job Roles,experience_years,skills,company_size
0,3.8,Sasken,Android Developer,400000,3,Bangalore,Full Time,Android,11,"['Java', 'Kotlin', 'Android SDK']",Small
1,4.5,Advanced Millennium Technologies,Android Developer,400000,3,Bangalore,Full Time,Android,11,"['Java', 'Kotlin', 'Android SDK']",Small
2,4.0,Unacademy,Android Developer,1000000,3,Bangalore,Full Time,Android,7,"['Java', 'Kotlin', 'Android SDK']",Mid
3,3.8,SnapBizz Cloudtech,Android Developer,300000,3,Bangalore,Full Time,Android,7,"['Java', 'Kotlin', 'Android SDK']",Small
4,4.4,Appoids Tech Solutions,Android Developer,600000,3,Bangalore,Full Time,Android,8,"['Java', 'Kotlin', 'Android SDK']",Mid

In [33]:
df=pd.get_dummies(df,columns=["Employment Status"],drop_first=True)
df.head()

,Rating,Company Name,Job Title,Salary,Salaries Reported,Location,Job Roles,experience_years,skills,company_size,Employment Status_Full Time,Employment Status_Intern,Employment Status_Trainee
0,3.8,Sasken,Android Developer,400000,3,Bangalore,Android,11,"['Java', 'Kotlin', 'Android SDK']",Small,True,False,False
1,4.5,Advanced Millennium Technologies,Android Developer,400000,3,Bangalore,Android,11,"['Java', 'Kotlin', 'Android SDK']",Small,True,False,False
2,4.0,Unacademy,Android Developer,1000000,3,Bangalore,Android,7,"['Java', 'Kotlin', 'Android SDK']",Mid,True,False,False
3,3.8,SnapBizz Cloudtech,Android Developer,300000,3,Bangalore,Android,7,"['Java', 'Kotlin', 'Android SDK']",Small,True,False,False
4,4.4,Appoids Tech Solutions,Android Developer,600000,3,Bangalore,Android,8,"['Java', 'Kotlin', 'Android SDK']",Mid,True,False,False

In [34]:
df.drop(columns=["Company Name"],inplace=True)
df.head(5)

,Rating,Job Title,Salary,Salaries Reported,Location,Job Roles,experience_years,skills,company_size,Employment Status_Full Time,Employment Status_Intern,Employment Status_Trainee
0,3.8,Android Developer,400000,3,Bangalore,Android,11,"['Java', 'Kotlin', 'Android SDK']",Small,True,False,False
1,4.5,Android Developer,400000,3,Bangalore,Android,11,"['Java', 'Kotlin', 'Android SDK']",Small,True,False,False
2,4.0,Android Developer,1000000,3,Bangalore,Android,7,"['Java', 'Kotlin', 'Android SDK']",Mid,True,False,False
3,3.8,Android Developer,300000,3,Bangalore,Android,7,"['Java', 'Kotlin', 'Android SDK']",Small,True,False,False
4,4.4,Android Developer,600000,3,Bangalore,Android,8,"['Java', 'Kotlin', 'Android SDK']",Mid,True,False,False

In [35]:
def map_job_category(title):
    title = title.lower()

    if "android" in title:
        return "android"
    elif "ios" in title:
        return "ios"
    elif "backend" in title:
        return "backend"
    elif "frontend" in title:
        return "frontend"
    elif "python" in title:
        return "python"
    elif "java" in title:
        return "java"
    elif "data" in title:
        return "data"
    elif "test" in title:
        return "testing"
    else:
        return "other"

df["job_category"] = df["Job Roles"].apply(map_job_category)
df.drop(columns=["Job Roles"], inplace=True)

In [36]:
df.head(5)

,Rating,Job Title,Salary,Salaries Reported,Location,experience_years,skills,company_size,Employment Status_Full Time,Employment Status_Intern,Employment Status_Trainee,job_category
0,3.8,Android Developer,400000,3,Bangalore,11,"['Java', 'Kotlin', 'Android SDK']",Small,True,False,False,android
1,4.5,Android Developer,400000,3,Bangalore,11,"['Java', 'Kotlin', 'Android SDK']",Small,True,False,False,android
2,4.0,Android Developer,1000000,3,Bangalore,7,"['Java', 'Kotlin', 'Android SDK']",Mid,True,False,False,android
3,3.8,Android Developer,300000,3,Bangalore,7,"['Java', 'Kotlin', 'Android SDK']",Small,True,False,False,android
4,4.4,Android Developer,600000,3,Bangalore,8,"['Java', 'Kotlin', 'Android SDK']",Mid,True,False,False,android

In [37]:
clm=["Location","company_size","job_category"]
df=pd.get_dummies(df,columns=clm,drop_first=True)
df.head(2)

,Rating,Job Title,Salary,Salaries Reported,experience_years,skills,Employment Status_Full Time,Employment Status_Intern,Employment Status_Trainee,Location_Chennai,Location_Hyderabad,Location_Jaipur,Location_Kerala,Location_Kolkata,Location_Madhya Pradesh,Location_Mumbai,Location_New Delhi,Location_Pune,company_size_Mid,company_size_Small,job_category_backend,job_category_data,job_category_frontend,job_category_ios,job_category_java,job_category_other,job_category_python,job_category_testing
0,3.8,Android Developer,400000,3,11,"['Java', 'Kotlin', 'Android SDK']",True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
1,4.5,Android Developer,400000,3,11,"['Java', 'Kotlin', 'Android SDK']",True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False

In [38]:
to_int=["Employment Status_Full Time",	"Employment Status_Intern",	"Employment Status_Trainee",	"Location_Chennai",	"Location_Hyderabad"	,"Location_Jaipur"	,"Location_Kerala"	,"Location_Kolkata",	"Location_Madhya Pradesh",	"Location_Mumbai"	,"Location_New Delhi"	,"Location_Pune"	,"company_size_Mid"	,"company_size_Small",	"job_category_backend"	,"job_category_data"	,"job_category_frontend"	,"job_category_ios",	"job_category_java"	,"job_category_other"	,"job_category_python"	,"job_category_testing"]
df[to_int]=df[to_int].astype(int)
df.head(2)

,Rating,Job Title,Salary,Salaries Reported,experience_years,skills,Employment Status_Full Time,Employment Status_Intern,Employment Status_Trainee,Location_Chennai,Location_Hyderabad,Location_Jaipur,Location_Kerala,Location_Kolkata,Location_Madhya Pradesh,Location_Mumbai,Location_New Delhi,Location_Pune,company_size_Mid,company_size_Small,job_category_backend,job_category_data,job_category_frontend,job_category_ios,job_category_java,job_category_other,job_category_python,job_category_testing
0,3.8,Android Developer,400000,3,11,"['Java', 'Kotlin', 'Android SDK']",1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,4.5,Android Developer,400000,3,11,"['Java', 'Kotlin', 'Android SDK']",1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0